name: BraveNewCoin
favicon: null
layout_spectrum: 0.6945643594954163
typography_spectrum: 0.5540518087800592
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.2877443744800985
  lightness: 0.9358699896838516
  saturation: 0.1835743288975209
  rhythmicContrast: 0.5118964314460754
purpose: []
