name: BraveNewCoin
favicon: null
layout_spectrum: 0.5076
typography_spectrum: 0.2208
title: Brave New Coin
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#231f20'
    - '#ffffff'
    - '#ff6600'
    - '#8a3f11'
    - '#cbcaca'
  brandStrength: 1
  lightness: 0.9358699896838516
  saturation: 0.1835743288975209
  rhythmicContrast: 0.5118964314460754
purpose: []
